name = "detroit_at_work"
description = "Detroit at Work publishes data about jobs and trainings available, these tools gather and organize that information."
schema = "detroit_at_work"

[tables.trainings]
name="trainings"
description = "Detroit at Work promotes a variety of training programs in fields such as healthcare, IT, transportation, skilled trades, and manufacturing. We are interested in the Training Programs related to IT. "
unit_of_analysis = "Training promoted by Detroit at work"
universe = "Training courses"
owner = "Detroit at Work"
collector = "Detroit at Work"
collection_reason = "To connect job seekers with trainings"
source_url = "https://detroitatwork.com/training"

[[tables.trainings.variables]]
name = "provider"
description = "The organization providing the training"

[[tables.trainings.variables]]
name = "program"
description = "The name of the program being provided"

[[tables.trainings.variables]]
name = "location"
description = "The address of the training"

[[tables.trainings.variables]]
name = "clinical_location"
description = "Unsure (MV) (mostly null)"

[[tables.trainings.variables]]
name = "phone"
description = "The phone number of the provider"

[[tables.trainings.variables]]
name = "website"
description = "Website for the provider"

[[tables.trainings.variables]]
name = "description"
description = "The description of the training"

[[tables.trainings.variables]]
name = "reading_grade_level"
description = "The reading grade level expected for the training"

[[tables.trainings.variables]]
name = "math_grade_level"
description = "The math grade level expected for the training"

[[tables.trainings.variables]]
name = "convictions_prohibited"
description = "Convictions, if any, that prohibit students from attending the course"

[[tables.trainings.variables]]
name = "other_requirements"
description = "Other requirements for the course."

[[tables.trainings.variables]]
name = "required_supplies"
description = "Supplies ('laptop' for instance) that are required to participate in the course."

[[tables.trainings.variables]]
name = "weeks"
description = "Number of weeks of the course"

[[tables.trainings.variables]]
name = "total_hours"
description = "Total hours of coursework"

[[tables.trainings.variables]]
name = "schedule"
description = "Schedule for the course"

[[tables.trainings.variables]]
name = "max_students"
description = "Maximum number of students allowed in each class"

[[tables.trainings.variables]]
name = "students_per_instructor"
description = "Number of students per instructor in each course"

[[tables.trainings.variables]]
name = "completion_rate"
description = "Percentage of students who complete the training program"

[[tables.trainings.variables]]
name = "placement_rate"
description = "Percentage of graduates who are placed in employment related to their training within 120 days of completing the program Training Related"

[[tables.trainings.variables]]
name = "credential_attainment_rate"
description = "Percentage of students who complete the training program and earn an industry recognized certification or license"

[[tables.trainings.variables]]
name = "credential_earned"
description = "Credentials graduates earn"

[[tables.trainings.variables]]
name = "occupations_prepared_for"
description = "Occupations graduates will be prepared to enter"

[[tables.trainings.variables]]
name = "average_grad_occ_wage"
description = "The average wage of the occupations the graduate is trained for"

[[tables.trainings.variables]]
name = "hs_diploma_required"
description = "High School Diploma / GED required to enroll"

[[tables.trainings.variables]]
name = "drug_screen_required"
description = "A drug screen is required for enrollment"

[[tables.trainings.variables]]
name = "background_check_required"
description = "A background check is required for enrollment"

[[tables.trainings.variables]]
name = "valid_drivers_license_required"
description = "A valid drivers license is required for enrollment"

[[tables.trainings.variables]]
name = "exam"
description = "There is an exam at the end of the training"

[[tables.trainings.variables]]
name = "equipment_trained_on"
description = "Equipment graduates will be trained to use"

[[tables.trainings.variables]]
name = "in_person_online"
description = "Is the training in person, online or hybrid?"

[tables.trainings.editions.2025-01-01]
edition_date = "2025-01-01"
notes = "First upload of this dataset"
raw_path = "V:\\DATA\\Business and employment\\Detroit at Work\\Data\\Raw\\trainings_scape_20241216.csv"
start = "2024-12-01"
end = "9999-12-31" # Forever
published = "2024-12-01"
acquired = "2024-12-16"